name: Generic Backend CI

on:
  push:
    branches:
      - main
  pull_request:
jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: |
              npm ci 
              cd cil-lib
              npm ci
              npm run test
  
  build:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'
    steps:
    - uses: actions/checkout@v2
    - name: Build docker image
      run: docker build --tag cil-api:latest .